# Generated by Django 4.2.7 on 2025-11-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the background video', max_length=200)),
                ('video', models.FileField(help_text='Upload background video for login/registration pages. Supports 4K videos. Recommended formats: MP4, WebM', upload_to='login_backgrounds/')),
                ('is_active', models.BooleanField(default=False, help_text='Set as active background video')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Background Video',
                'verbose_name_plural': 'Login Background Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
