# Generated by Django 4.2.7 on 2025-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(default='colored', max_length=50),
        ),
    ]
