# Generated by Django 4.2.7 on 2025-11-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Calibri', 'Calibri'), ('Roboto', 'Roboto')], default='Arial', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='resume',
            name='line_spacing',
            field=models.DecimalField(decimal_places=1, default=1.4, max_digits=3),
        ),
        migrations.AddField(
            model_name='resume',
            name='primary_color',
            field=models.CharField(default='#667eea', max_length=7),
        ),
        migrations.AddField(
            model_name='resume',
            name='secondary_color',
            field=models.CharField(default='#764ba2', max_length=7),
        ),
        migrations.AddField(
            model_name='resume',
            name='section_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('Elementary', 'Elementary'), ('Limited Working', 'Limited Working'), ('Professional Working', 'Professional Working'), ('Full Professional', 'Full Professional'), ('Native', 'Native/Bilingual')], max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sections', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
    ]
